FROM ubuntu

RUN apt-get update
RUN apt-get -y install bash iproute2 net-tools tcpdump vim iputils-ping
RUN apt-get clean

COPY OSPF_setup.sh OSPF_setup.sh
RUN chmod +x OSPF_setup.sh
RUN OSPF_setup.sh

CMD ["bash"]